#!/bin/bash

# Sketchybar Configuration with Catppuccin Mocha Theme
# https://github.com/catppuccin/catppuccin

# Source colors
source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
sketchybar --bar \
    position=top \
    height=32 \
    margin=4 \
    y_offset=4 \
    corner_radius=9 \
    blur_radius=20 \
    color=$BAR_COLOR

##### Default Item Styles #####
default=(
    padding_left=4
    padding_right=4
    icon.font="Hack Nerd Font:Bold:14.0"
    label.font="Hack Nerd Font:Bold:11.0"
    icon.color=$TEXT
    label.color=$TEXT
    icon.padding_left=6
    icon.padding_right=4
    label.padding_left=4
    label.padding_right=6
    background.color=$ITEM_BG_COLOR
    background.corner_radius=6
    background.height=24
)
sketchybar --default "${default[@]}"

##### Left Side - Aerospace Workspaces #####
sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        background.color=$SURFACE0 \
        background.corner_radius=6 \
        background.height=24 \
        background.drawing=on \
        label="$sid" \
        label.color=$TEXT \
        icon.drawing=off \
        click_script="aerospace workspace $sid" \
        script="$PLUGIN_DIR/aerospace.sh $sid"
done

##### Right Side - System Information #####

# Volume
sketchybar --add item volume right \
    --set volume \
    update_freq=1 \
    script="$PLUGIN_DIR/volume.sh" \
    --subscribe volume volume_change

# WiFi
sketchybar --add item wifi right \
    --set wifi \
    update_freq=10 \
    script="$PLUGIN_DIR/wifi.sh" \
    --subscribe wifi wifi_change system_woke

# Battery
sketchybar --add item battery right \
    --set battery \
    update_freq=30 \
    script="$PLUGIN_DIR/battery.sh" \
    --subscribe battery power_source_change system_woke

# Clock
sketchybar --add item clock right \
    --set clock \
    update_freq=30 \
    script="$PLUGIN_DIR/clock.sh"

##### Finalize Configuration #####
sketchybar --update
